name: Docker Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: addnab/docker-run-action@v3
        with:
          image: nerdfonts/patcher:latest
          options: --rm -v ./lig:/in -v ./out:/out nerdfonts/patcher -c
      - name: Bundle
        run: |
          zip -r lig.zip out
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Release $$'
          prerelease: false
          files: |
            lig.zip
